#db: mvp_m5_gnorambuena
db.url=jdbc:mysql://localhost:3306/mvp_m5_gnorambuena?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# user y pass deberían estar en el .env para no subirlo al repo; solo son de prueba.
db.user=mvp_m5
db.password=mvp_m5_1234

#driver bd
db.driver=com.mysql.cj.jdbc.Driver

