-- *****************************
-- IMPORTANTE
-- CREA LA NUEVA BASE DE DATOS
CREATE DATABASE IF NOT EXISTS mvp_m5_gnorambuena;

-- IMPORTANTE
-- CREA EL USUARIO A UTILIZAR, DEFINIDO EN DATABASE.PROPERTIES
-- CON PERMISOS PARA EL CRUD BÁSICO
CREATE USER 'mvp_m5'@'localhost' IDENTIFIED BY 'mvp_m5_1234';

GRANT SELECT, INSERT, UPDATE, DELETE ON mvp_m5_gnorambuena.* TO 'mvp_m6'@'localhost';

-- *****************************

-- USA LA BASE DE DATOS CREADA
USE mvp_m5_gnorambuena;

-- CREACIÓN TABLA CUSTOMERS
CREATE TABLE CUSTOMERS (
	ID SERIAL,
	NAME VARCHAR(50),
	RUT VARCHAR(12) UNIQUE NOT NULL,
	EMAIL VARCHAR(50) UNIQUE NOT NULL,
	CELLPHONE VARCHAR(12) NOT NULL,
	-- LA CONTRASEÑA DEBERÍA SER UN HASH
	PASS_HASH VARCHAR(100) NOT NULL,

	CONSTRAINT PK_CUSTOMERS PRIMARY KEY (ID)
);

-- CREACIÓN TABLA ORDERS
CREATE TABLE ORDERS (
	ID SERIAL,
	CUSTOMER_ID BIGINT UNSIGNED NOT NULL,
	CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	TOTAL DECIMAL CHECK (TOTAL > 0.0),

	CONSTRAINT PK_ORDERS PRIMARY KEY (ID),
	CONSTRAINT FK_ORDERS_CUSTOMERS FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID) ON DELETE CASCADE
);

-- CREACIÓN TABLA CATEGORIES
CREATE TABLE CATEGORIES (
	ID SERIAL,
	NAME VARCHAR(40) NOT NULL,

	CONSTRAINT PK_CATEGORIES PRIMARY KEY (ID)
);

CREATE TABLE BRANDS (
	ID SERIAL,
	NAME VARCHAR(40) NOT NULL,

	CONSTRAINT PK_BRANDS PRIMARY KEY (ID)
);

-- CREACIÓN TABLA PRODUCTOS
CREATE TABLE PRODUCTS (
	ID SERIAL,
    BRAND_ID BIGINT UNSIGNED NOT NULL,
    CATEGORY_ID BIGINT UNSIGNED NOT NULL,
    URL_IMAGE VARCHAR(500),
    STOCK INT NOT NULL CHECK (STOCK >= 0),
    NAME VARCHAR(40) NOT NULL,
    FEATURES JSON NOT NUll,
    PRICE DECIMAL NOT NULL CHECK (PRICE > 0.0),
	DESCRIPTION VARCHAR(1000),
    SHORT_DESCRIPTION VARCHAR(100),

	CONSTRAINT PK_PRODUCTS PRIMARY KEY (ID),
	CONSTRAINT FK_PRODUCTS_CATEGORIES FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID),
    CONSTRAINT FK_PRODUCTS_BRANDS FOREIGN KEY (BRAND_ID) REFERENCES BRANDS (ID)
);

-- CREACIÓN TABLA ORDERS_ITEM
CREATE TABLE ORDERS_ITEM (
	ID SERIAL,
	ORDER_ID BIGINT UNSIGNED NOT NULL,
	PRODUCT_ID BIGINT UNSIGNED NOT NULL,
	UNIT_PRICE DECIMAL NOT NULL CHECK (UNIT_PRICE > 0.0),
	QUANTITY INTEGER NOT NULL CHECK (QUANTITY > 0),
	SUB_TOTAL DECIMAL GENERATED ALWAYS AS (UNIT_PRICE * QUANTITY) STORED,

	CONSTRAINT PK_ORDERS_ITEM PRIMARY KEY (ID),
	CONSTRAINT FK_ORDERS_ITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID) ON DELETE CASCADE,
	CONSTRAINT FK_ORDERS_ITEM_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID)
);